# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "matrix.example.localhost"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: synapse
    password: STRONG_PASSWORD
    database: synapse
    host: postgres
    cp_min: 5
    cp_max: 10
log_config: "/data/matrix.example.localhost.log.config"
media_store_path: /data/media_store
registration_shared_secret: "fg5JZwz_RrnlI6wQ40GRY:4loB5w7dTRC,#radDlDrhEy0r078"
report_stats: true
macaroon_secret_key: "2xi0TZYoj#s_#d7dNOuyHnf@9gu=-z4RKU+VB._5Qo:NaNgpsK"
form_secret: "u.V~t1g6fygdin+4jZ#G2;9PNx@bc.:C+W11p3Bf3*BB;fhF9~"
signing_key_path: "/data/matrix.example.localhost.signing.key"

enable_registration: true
enable_registration_without_verification: true
default_identity_server: https://matrix.org

trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml